apiVersion: skaffold/v1
kind: Config
metadata:
  name: de-graphql
deploy:
  kubectl:
    manifests:
    - k8s/de-graphql.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: discoenv/de-graphql
  local: {}
